### ISSUE TITLE
Installation Problem SU2 7.0.5

### ISSUE THREAD

**Issue by flybob91** [su2code/SU2#1019]
Hello SU2 developers, 
I tried to build from source the new SU2 v7.0.5 by following the quick compilation guide but after the command

`./meson.py build`

I received the following error

```
Downloading CoDiPack '501dcf0305df147481630f20ce37c2e624fb351f'
Downloading MeDiPack 'edde14f9ac4026b72b1e130f61c0a78e8652afa5'
Downloading meson '29ef4478df6d3aaca40c7993f125b29409be1de2'
Downloading ninja '52649de2c56b63f42bc59513d51286531c595b44'
ninja executable not found. Building ...
bootstrapping ninja...
warning: A compatible version of re2c (>= 0.11.3) was not found; changes to src/*.in.cc will not affect your build.
wrote build.ninja.
bootstrap complete.  rebuilding...
[29/29] LINK ninja
The Meson build system
Version: 0.54.999
Source dir: /home/roby/SU2/SU2v7
Build dir: /home/roby/SU2/SU2v7/build
Build type: native build
Project name: SU2
Project version: 7.0.5 "Blackbird"
C compiler for the host machine: cc (gcc 5.4.0 "cc (Ubuntu 5.4.0-6ubuntu1~16.04.12) 5.4.0 20160609")
C linker for the host machine: cc ld.bfd 2.26.1
C++ compiler for the host machine: c++ (gcc 5.4.0 "c++ (Ubuntu 5.4.0-6ubuntu1~16.04.12) 5.4.0 20160609")
C++ linker for the host machine: c++ ld.bfd 2.26.1
Host machine cpu family: x86_64
Host machine cpu: x86_64
Program python3 found: YES (/usr/bin/python3)
Found pkg-config: /usr/bin/pkg-config (0.29.1)
Run-time dependency MPI for c found: YES 1.10.2
Run-time dependency MPI for cpp found: YES 1.10.2
Message: Extracting boost ...

externals/tecio/meson.build:6:2: ERROR: Command "/usr/bin/python3 /home/roby/SU2/SU2v7/meson_scripts/extract_file.py boost.tar.gz /home/roby/SU2/SU2v7/externals/tecio" failed with status 1.

A full log can be found at /home/roby/SU2/SU2v7/build/meson-logs/meson-log.txt
```

Best regards

**Comment by talbring** [comment]
Can you post a little bit more information? And have a look also at the full log.

**Comment by flybob91** [comment]
Hello Tim. Thank you for the quick reply. 
Since I'm a new SU2 user, I firstly tried to build it from source in the quickest possible way so I didn't really do much. I've just run the command `./meson.py build` wihout modifying anything. Furthermore I tried on two different machines and I got the same error. 
Here the last part of the meson-log.txt but unfortunately it doesn't add more information about the problem

```
Compiler stderr:
 
Run-time dependency MPI for cpp found: YES 1.10.2
Running command: /usr/bin/python3 /home/roby/SU2/SU2v7/meson_scripts/check_dir.py boost
--- stdout ---

--- stderr ---


Message: Extracting boost ...
Running command: /usr/bin/python3 /home/roby/SU2/SU2v7/meson_scripts/extract_file.py boost.tar.gz /home/roby/SU2/SU2v7/externals/tecio
--- stdout ---
/home/roby/SU2/SU2v7/externals/tecio

--- stderr ---
Traceback (most recent call last):
  File "/home/roby/SU2/SU2v7/meson_scripts/extract_file.py", line 38, in <module>
    extract_tar(infile, P.outpath, True)
  File "/home/roby/SU2/SU2v7/meson_scripts/extract_file.py", line 24, in extract_tar
    with tarfile.open(fn) as z:
  File "/usr/lib/python3.5/tarfile.py", line 1557, in open
    return func(name, "r", fileobj, **kwargs)
  File "/usr/lib/python3.5/tarfile.py", line 1655, in bz2open
    compresslevel=compresslevel)
  File "/usr/lib/python3.5/bz2.py", line 102, in __init__
    raise TypeError("filename must be a str or bytes object, or a file")
TypeError: filename must be a str or bytes object, or a file



externals/tecio/meson.build:6:2: ERROR: Command "/usr/bin/python3 /home/roby/SU2/SU2v7/meson_scripts/extract_file.py boost.tar.gz /home/roby/SU2/SU2v7/externals/tecio" failed with status 1.
```

Thank you for the assistance

**Comment by talbring** [comment]
Hm that seems to be an issue with python 3.5. Do you have access to python3.7? Otherwise manually extract the archive file by going to folder externals/tecio/ and using the command
```
tar xzf boost.tar.gz 
```
Then try to rerun meson.py again.

**Comment by flybob91** [comment]
Thank you for helping me Tim. You are right. 
Problem solved now.
