### ISSUE TITLE
Error when building from source

### ISSUE THREAD

**Issue by BBurke123** [su2code/SU2#1042]
I am trying to install the newest version of SU2 on our computing cluster; previously I have been running SU2 v6.2. I have successfully installed swig:
```
$ swig -version

SWIG Version 2.0.10

Compiled with g++ [x86_64-redhat-linux-gnu]

Configured options: +pcre
```
When I installed mpi4py, I had to install it with the `--user` flag: `$ pip install mpi4py --user`. I then edited my bash file to include the new python path. I have since run into the following error when trying to run `./meson.py`. I am using Python 3.6.8.

**Meson Output**
```
$ python3 ./meson.py build
ninja executable not found. Building ...
bootstrapping ninja...
icpc: command line remark #10148: option '-fdiagnostics-color' not supported
remark #11074: Inlining inhibited by limit max-total-size 
remark #11076: To get full report use -qopt-report=4 -qopt-report-phase ipo
warning: A compatible version of re2c (>= 0.11.3) was not found; changes to src/*.in.cc will not affect your build.
icpc: command line remark #10148: option '-fdiagnostics-color' not supported
remark #11074: Inlining inhibited by limit max-size 
remark #11074: Inlining inhibited by limit max-total-size 
remark #11076: To get full report use -qopt-report=4 -qopt-report-phase ipo
icpc: command line remark #10148: option '-fdiagnostics-color' not supported
remark #11074: Inlining inhibited by limit max-size 
remark #11076: To get full report use -qopt-report=4 -qopt-report-phase ipo
icpc: command line remark #10148: option '-fdiagnostics-color' not supported
remark #11074: Inlining inhibited by limit max-size 
remark #11076: To get full report use -qopt-report=4 -qopt-report-phase ipo
icpc: command line remark #10148: option '-fdiagnostics-color' not supported
icpc: command line remark #10148: option '-fdiagnostics-color' not supported
icpc: command line remark #10148: option '-fdiagnostics-color' not supported
icpc: command line remark #10148: option '-fdiagnostics-color' not supported
remark #11074: Inlining inhibited by limit max-size 
remark #11076: To get full report use -qopt-report=4 -qopt-report-phase ipo
icpc: command line remark #10148: option '-fdiagnostics-color' not supported
remark #11074: Inlining inhibited by limit max-size 
remark #11076: To get full report use -qopt-report=4 -qopt-report-phase ipo
icpc: command line remark #10148: option '-fdiagnostics-color' not supported
remark #11074: Inlining inhibited by limit max-size 
remark #11074: Inlining inhibited by limit max-total-size 
remark #11076: To get full report use -qopt-report=4 -qopt-report-phase ipo
icpc: command line remark #10148: option '-fdiagnostics-color' not supported
remark #11074: Inlining inhibited by limit max-size 
remark #11076: To get full report use -qopt-report=4 -qopt-report-phase ipo
icpc: command line remark #10148: option '-fdiagnostics-color' not supported
icpc: command line remark #10148: option '-fdiagnostics-color' not supported
icpc: command line remark #10148: option '-fdiagnostics-color' not supported
remark #11074: Inlining inhibited by limit max-size 
remark #11076: To get full report use -qopt-report=4 -qopt-report-phase ipo
icpc: command line remark #10148: option '-fdiagnostics-color' not supported
remark #11074: Inlining inhibited by limit max-size 
remark #11076: To get full report use -qopt-report=4 -qopt-report-phase ipo
icpc: command line remark #10148: option '-fdiagnostics-color' not supported
remark #11074: Inlining inhibited by limit max-size 
remark #11076: To get full report use -qopt-report=4 -qopt-report-phase ipo
icpc: command line remark #10148: option '-fdiagnostics-color' not supported
icpc: command line remark #10148: option '-fdiagnostics-color' not supported
remark #11074: Inlining inhibited by limit max-size 
remark #11074: Inlining inhibited by limit max-total-size 
remark #11076: To get full report use -qopt-report=4 -qopt-report-phase ipo
icpc: command line remark #10148: option '-fdiagnostics-color' not supported
icpc: command line remark #10148: option '-fdiagnostics-color' not supported
icpc: command line remark #10148: option '-fdiagnostics-color' not supported
remark #11074: Inlining inhibited by limit max-size 
remark #11074: Inlining inhibited by limit max-total-size 
remark #11076: To get full report use -qopt-report=4 -qopt-report-phase ipo
icpc: command line remark #10148: option '-fdiagnostics-color' not supported
icpc: command line remark #10148: option '-fdiagnostics-color' not supported
./src/util.cc(158): warning #3656: variable "components" may be used before its value is set
            dst = components[component_count - 1];
                  ^

icpc: command line remark #10148: option '-fdiagnostics-color' not supported
icpc: command line remark #10148: option '-fdiagnostics-color' not supported
remark #11074: Inlining inhibited by limit max-size 
remark #11076: To get full report use -qopt-report=4 -qopt-report-phase ipo
icpc: command line remark #10148: option '-fdiagnostics-color' not supported
./src/ninja.cc(119): warning #177: function "<unnamed>::NinjaMain::ToolMSVC" was declared but never referenced
    int ToolMSVC(const Options* options, int argc, char* argv[]);
        ^

remark #11074: Inlining inhibited by limit max-size 
remark #11074: Inlining inhibited by limit max-total-size 
remark #11076: To get full report use -qopt-report=4 -qopt-report-phase ipo
wrote build.ninja.
bootstrap complete.  rebuilding...
[2/29] CXX build/metrics.o
icpc: command line remark #10148: option '-fdiagnostics-color' not supported
[3/29] CXX build/clparser.o
icpc: command line remark #10148: option '-fdiagnostics-color' not supported
[4/29] CXX build/disk_interface.o
icpc: command line remark #10148: option '-fdiagnostics-color' not supported
remark #11074: Inlining inhibited by limit max-size 
remark #11076: To get full report use -qopt-report=4 -qopt-report-phase ipo
[5/29] CXX build/depfile_parser.o
icpc: command line remark #10148: option '-fdiagnostics-color' not supported
[6/29] CXX build/debug_flags.o
icpc: command line remark #10148: option '-fdiagnostics-color' not supported
[7/29] CXX build/deps_log.o
icpc: command line remark #10148: option '-fdiagnostics-color' not supported
remark #11074: Inlining inhibited by limit max-size 
remark #11076: To get full report use -qopt-report=4 -qopt-report-phase ipo
[8/29] CXX build/browse.o
icpc: command line remark #10148: option '-fdiagnostics-color' not supported
remark #11074: Inlining inhibited by limit max-total-size 
remark #11076: To get full report use -qopt-report=4 -qopt-report-phase ipo
[9/29] CXX build/parser.o
icpc: command line remark #10148: option '-fdiagnostics-color' not supported
[10/29] CXX build/line_printer.o
icpc: command line remark #10148: option '-fdiagnostics-color' not supported
[11/29] CXX build/string_piece_util.o
icpc: command line remark #10148: option '-fdiagnostics-color' not supported
[12/29] CXX build/edit_distance.o
icpc: command line remark #10148: option '-fdiagnostics-color' not supported
[13/29] CXX build/lexer.o
icpc: command line remark #10148: option '-fdiagnostics-color' not supported
remark #11074: Inlining inhibited by limit max-size 
remark #11076: To get full report use -qopt-report=4 -qopt-report-phase ipo
[14/29] CXX build/graphviz.o
icpc: command line remark #10148: option '-fdiagnostics-color' not supported
remark #11074: Inlining inhibited by limit max-size 
remark #11076: To get full report use -qopt-report=4 -qopt-report-phase ipo
[15/29] CXX build/version.o
icpc: command line remark #10148: option '-fdiagnostics-color' not supported
[16/29] CXX build/dyndep.o
icpc: command line remark #10148: option '-fdiagnostics-color' not supported
remark #11074: Inlining inhibited by limit max-size 
remark #11074: Inlining inhibited by limit max-total-size 
remark #11076: To get full report use -qopt-report=4 -qopt-report-phase ipo
[17/29] CXX build/clean.o
icpc: command line remark #10148: option '-fdiagnostics-color' not supported
remark #11074: Inlining inhibited by limit max-size 
remark #11076: To get full report use -qopt-report=4 -qopt-report-phase ipo
[18/29] CXX build/util.o
icpc: command line remark #10148: option '-fdiagnostics-color' not supported
src/util.cc(158): warning #3656: variable "components" may be used before its value is set
            dst = components[component_count - 1];
                  ^

[19/29] CXX build/eval_env.o
icpc: command line remark #10148: option '-fdiagnostics-color' not supported
[20/29] CXX build/dyndep_parser.o
icpc: command line remark #10148: option '-fdiagnostics-color' not supported
remark #11074: Inlining inhibited by limit max-size 
remark #11076: To get full report use -qopt-report=4 -qopt-report-phase ipo
[21/29] CXX build/subprocess-posix.o
icpc: command line remark #10148: option '-fdiagnostics-color' not supported
remark #11074: Inlining inhibited by limit max-size 
remark #11076: To get full report use -qopt-report=4 -qopt-report-phase ipo
[22/29] CXX build/build_log.o
icpc: command line remark #10148: option '-fdiagnostics-color' not supported
remark #11074: Inlining inhibited by limit max-size 
remark #11076: To get full report use -qopt-report=4 -qopt-report-phase ipo
[23/29] CXX build/graph.o
icpc: command line remark #10148: option '-fdiagnostics-color' not supported
remark #11074: Inlining inhibited by limit max-size 
remark #11076: To get full report use -qopt-report=4 -qopt-report-phase ipo
[24/29] CXX build/state.o
icpc: command line remark #10148: option '-fdiagnostics-color' not supported
remark #11074: Inlining inhibited by limit max-size 
remark #11074: Inlining inhibited by limit max-total-size 
remark #11076: To get full report use -qopt-report=4 -qopt-report-phase ipo
[25/29] CXX build/manifest_parser.o
icpc: command line remark #10148: option '-fdiagnostics-color' not supported
remark #11074: Inlining inhibited by limit max-size 
remark #11074: Inlining inhibited by limit max-total-size 
remark #11076: To get full report use -qopt-report=4 -qopt-report-phase ipo
[26/29] CXX build/ninja.o
icpc: command line remark #10148: option '-fdiagnostics-color' not supported
src/ninja.cc(119): warning #177: function "<unnamed>::NinjaMain::ToolMSVC" was declared but never referenced
    int ToolMSVC(const Options* options, int argc, char* argv[]);
        ^

remark #11074: Inlining inhibited by limit max-size 
remark #11074: Inlining inhibited by limit max-total-size 
remark #11076: To get full report use -qopt-report=4 -qopt-report-phase ipo
[27/29] CXX build/build.o
icpc: command line remark #10148: option '-fdiagnostics-color' not supported
remark #11074: Inlining inhibited by limit max-size 
remark #11074: Inlining inhibited by limit max-total-size 
remark #11076: To get full report use -qopt-report=4 -qopt-report-phase ipo
[29/29] LINK ninja
Traceback (most recent call last):
  File "./meson.py", line 85, in <module>
    sys.exit(mesonmain.main())
  File "/depot/data/SU2_v7/SU2-v7_modified/externals/meson/mesonbuild/mesonmain.py", line 228, in main
    return run(sys.argv[1:], launcher)
  File "/depot/data/SU2_v7/SU2-v7_modified/externals/meson/mesonbuild/mesonmain.py", line 219, in run
    return CommandLineParser().run(args)
  File "/depot/data/SU2_v7/SU2-v7_modified/externals/meson/mesonbuild/mesonmain.py", line 44, in __init__
    help_msg='Configure the project')
  File "/depot/data/SU2_v7/SU2-v7_modified/externals/meson/mesonbuild/mesonmain.py", line 82, in add_command
    p = self.subparsers.add_parser(name, help=help_msg, aliases=aliases, formatter_class=self.formatter)
  File "/apps/cent7/xalt/libexec/argparse.py", line 1085, in add_parser
    parser = self._parser_class(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'aliases'
```

**Desktop:**
 - OS: CentOS x86-64 7.7
 - C++ compiler and version: Intel C++ 17.0.1.132
 - MPI implementation and version: IMPI 2017.1.132
 - SU2 Version: v7.0.5

**Comment by pcarruscag** [comment]
Have you tried the suggested python 3.7 on CFD online?
As a side note, your compiler version does not do one specific optimization that the finite volume solvers rely on (icpc 19.0.1 onward does).

**Comment by BBurke123** [comment]
I switched to gcc and had to delete "aliases=aliases" from line 82 of mesonmain.py in /externals/meson/mesonbuild, then I was able to build successfully.
