### ISSUE TITLE
meson.py failed to download Mutationpp (Building SU2-v7.1.0 tarball)

### ISSUE THREAD

**Issue by mercanca** [su2code/SU2#1191]
# Problem
While building the SU2-v7.1.0 tarball, The meson.py failed to download Mutationpp:
```
./meson.py build --prefix=/okyanus/progs/SU2/SU2-v7.1.0-python-3.8.7-mpich-3.4.1-gcc-8.3.0
Downloading CoDiPack '1b8d3f5f03de560fb63a2a76ad91ab7bb3fa67d8'
Downloading MeDiPack 'b84cef4272ab8bad981c0d0386d855daa8fbd340'
Downloading meson '29ef4478df6d3aaca40c7993f125b29409be1de2'
Downloading ninja '52649de2c56b63f42bc59513d51286531c595b44'
Downloading Mutationpp '5ff579f43781cae07411e5ab46291c9971536be6'
Traceback (most recent call last):
  File "./meson.py", line 71, in <module>
    init_submodules('auto')
  File "/okyanus/admin/paketler/su2code-SU2-790ded8/meson_scripts/init.py", line 95, in init_submodules
    download_module(mpp_name, alt_name_mpp, github_repo_mpp, sha_version_mpp)
  File "/okyanus/admin/paketler/su2code-SU2-790ded8/meson_scripts/init.py", line 172, in download_module
    urllib.request.urlretrieve (url, commit_sha + '.zip')
  File "/okyanus/progs/Python/Python-3.8.7-mpich-3.4.1-gcc-8.3.0/lib/python3.8/urllib/request.py", line 247, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "/okyanus/progs/Python/Python-3.8.7-mpich-3.4.1-gcc-8.3.0/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/okyanus/progs/Python/Python-3.8.7-mpich-3.4.1-gcc-8.3.0/lib/python3.8/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/okyanus/progs/Python/Python-3.8.7-mpich-3.4.1-gcc-8.3.0/lib/python3.8/urllib/request.py", line 640, in http_response
    response = self.parent.error(
  File "/okyanus/progs/Python/Python-3.8.7-mpich-3.4.1-gcc-8.3.0/lib/python3.8/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/okyanus/progs/Python/Python-3.8.7-mpich-3.4.1-gcc-8.3.0/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/okyanus/progs/Python/Python-3.8.7-mpich-3.4.1-gcc-8.3.0/lib/python3.8/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found
```
# Solution
You should edit meson_scripts/init.py file, and replace line56:
```
github_repo_mpp = 'https://github.com/mutationpp/Mutationpp.git'
```
with this line:
```
github_repo_mpp = 'https://github.com/mutationpp/Mutationpp'
```

# Environment
OS: Centos 7
SU2: SU2-v7.1.0
MPI: mpich-3.4.1
COMPILER: gcc-8.3.0
PYTHON: python-3.8.7

**Comment by pcarruscag** [comment]
Thank you for reporting, this is fixed in the develop branch, and is related with #1184 
I will keep this issue open until the next release as I imagine it will trip other folks.

**Comment by shikhar333** [comment]
Thanks for the solution.
