### ISSUE TITLE
Installing SU2 on a machine without internet access

### ISSUE THREAD

**Issue by SumanVajjala** [su2code/SU2#1335]
Hi,

I am trying to install SU2 v7.1.1 on a cluster without internet access. I have downloaded CoDiPack, MeDiPack, Meson, Ninja and Mutation modules in the root directory. However, when I run meson.py I get the following error:

Downloading CoDiPack '1b8d3f5f03de560fb63a2a76ad91ab7bb3fa67d8'
Traceback (most recent call last):
  File "/app/python-3.6.3/lib/python3.6/urllib/request.py", line 1318, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/app/python-3.6.3/lib/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/app/python-3.6.3/lib/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/app/python-3.6.3/lib/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/app/python-3.6.3/lib/python3.6/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/app/python-3.6.3/lib/python3.6/http/client.py", line 964, in send
    self.connect()
  File "/app/python-3.6.3/lib/python3.6/http/client.py", line 1392, in connect
    super().connect()
  File "/app/python-3.6.3/lib/python3.6/http/client.py", line 936, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "/app/python-3.6.3/lib/python3.6/socket.py", line 724, in create_connection
    raise err
  File "/app/python-3.6.3/lib/python3.6/socket.py", line 713, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./meson.py", line 71, in <module>
    init_submodules('auto')
  File "/home/vksuman/SU2-7.1.1/meson_scripts/init.py", line 91, in init_submodules
    download_module(codi_name, alt_name_codi, github_repo_codi, sha_version_codi)
  File "/home/vksuman/SU2-7.1.1/meson_scripts/init.py", line 172, in download_module
    urllib.request.urlretrieve (url, commit_sha + '.zip')
  File "/app/python-3.6.3/lib/python3.6/urllib/request.py", line 248, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "/app/python-3.6.3/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/app/python-3.6.3/lib/python3.6/urllib/request.py", line 526, in open
    response = self._open(req, data)
  File "/app/python-3.6.3/lib/python3.6/urllib/request.py", line 544, in _open
    '_open', req)
  File "/app/python-3.6.3/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/app/python-3.6.3/lib/python3.6/urllib/request.py", line 1361, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/app/python-3.6.3/lib/python3.6/urllib/request.py", line 1320, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 110] Connection timed out>

I have no idea why this is happening. I was able to install SU2 v7.0.3 this way. Any help regarding this will be greatly appreciated.

These are the modules in the root directory

MeDiPack-6aef76912e7099c4f08c9705848797ca9e8070da.zip    
CoDiPack-1b8d3f5f03de560fb63a2a76ad91ab7bb3fa67d8.zip  
meson-29ef4478df6d3aaca40c7993f125b29409be1de2.zip       
Mutationpp-5ff579f43781cae07411e5ab46291c9971536be6.zip  
ninja-52649de2c56b63f42bc59513d51286531c595b44.zip

Regards
Suman

**Comment by pcarruscag** [comment]
Right... I've finally fix this. The manual/offline build with meson will work in the next version.
For completeness, there is another way to work "offline", on a machine with internet access clone the SU2 repo using `git clone`, then run meson which will initialize the submodules, finally copy **everything** to the offline machine.
If this machine **has git** installed, it will detect that the submodules are present.
