### ISSUE TITLE
"options.filename == None" occurs in all .py files under windows10

### ISSUE THREAD

**Issue by HANSIeltsKing** [su2code/SU2#1567]
This is a SU2 user using Windows 10 system. When simulating the Tutorial Case, as long as SU2_CFD is used, it can be successfully simulated, but the parallel_computation.py required by my project cannot be used. Also, all simulations with ".py" files suffer from the same problem, i.e. "options.filename == None".

I wonder if this situation is a problem with the Python Wrapper? The tutorial does not mention its compilation method in Windows system. I would like to report how to use the parallel_computation.py in Windows system?

My SU2 version is v7.3.0.

I will be very appreciated if I could get some feedback on this issue.

**Comment by HANSIeltsKing** [comment]
When I enter the "shape_optimization.py -f unsteady_naca0012_opt.cfg" in the commend the error is:
```
Traceback (most recent call last):
  File "C:\Users\74351\Desktop\SU2\SU2\bin\test2\shape_optimization.py", line 116, in <module>
    main()
  File "C:\Users\74351\Desktop\SU2\SU2\bin\test2\shape_optimization.py", line 34, in main
    shape_optimization( options.filename    ,
  File "C:\Users\74351\Desktop\SU2\SU2\bin\test2\shape_optimization.py", line 51, in shape_optimization
    config = SU2.io.Config(filename)
  File "C:\Users\74351\Desktop\SU2\SU2\bin\SU2\io\config.py", line 88, in __init__
    super(Config,self).__init__(*args,**kwarg)
  File "C:\Users\74351\Desktop\SU2\SU2\bin\SU2\util\ordered_bunch.py", line 83, in __init__
    super(OrderedBunch,self).__init__(*args,**kwarg)
  File "C:\Users\74351\Desktop\SU2\SU2\bin\SU2\util\ordered_dict.py", line 48, in __init__
    self.__update(*args, **kwds)
  File "C:\Users\74351\Desktop\SU2\SU2\bin\SU2\util\ordered_dict.py", line 174, in update
    for key, value in other:
TypeError: 'NoneType' object is not iterable
```
When I enter the "parallel_computation.py -f turb_naca0012.cfg -n NP in the commend the error is:
```
Traceback (most recent call last):
  File "C:\Users\74351\Desktop\SU2\SU2\bin\parallel_computation.py", line 110, in <module>
    main()
  File "C:\Users\74351\Desktop\SU2\SU2\bin\parallel_computation.py", line 53, in main
    raise Exception("No config file provided. Use -f flag")
Exception: No config file provided. Use -f flag
```
Any solvers related to ".py" cannot be executed, but I can run any cases with SU2_CFD. So I wonder if this situation is a problem with the Python Wrapper? 

I will be very appreciated if I could get some feedback on this issue.
