### ISSUE TITLE
parmetis failing

### ISSUE THREAD

**Issue by aerialhedgehog** [su2code/SU2#159]
were any major changes made to the implementation of parmetis?  i'm getting segfaults during the 'call parmetis' step of SU2_CFD and SU2_DEF

**Comment by aerialhedgehog** [comment]
here's a trace from my ubuntu machine --
```
Traceback (most recent call last):
  File "/home/app/SU2/install/bin/parallel_computation.py", line 110, in <module>
    main()
  File "/home/app/SU2/install/bin/parallel_computation.py", line 61, in main
    options.compute      )
  File "/home/app/SU2/install/bin/parallel_computation.py", line 88, in parallel_computation
    info = SU2.run.CFD(config) 
RuntimeError:
Command = mpirun -n 12 /home/app/SU2/install/bin/SU2_CFD config_CFD.cfg
SU2 process returned error '15'
[ubuntu:8553] *** An error occurred in MPI_Wait
[ubuntu:8553] *** on communicator MPI COMMUNICATOR 3 DUP FROM 0
[ubuntu:8553] *** MPI_ERR_TRUNCATE: message truncated
[ubuntu:8553] *** MPI_ERRORS_ARE_FATAL: your MPI job will now abort
--------------------------------------------------------------------------
mpirun has exited due to process rank 9 with PID 8554 on
node ubuntu exiting improperly. There are two reasons this could occur:

1. this process did not call "init" before exiting, but others in
the job did. This can cause a job to hang indefinitely while it waits
for all processes to call "init". By rule, if one process calls "init",
then ALL processes must call "init" prior to termination.

2. this process called "init", but exited without calling "finalize".
By rule, all processes that call "init" MUST call "finalize" prior to
exiting or it will be considered an "abnormal termination"

This may have caused other processes in the application to be
terminated by signals sent by mpirun (as reported here).
--------------------------------------------------------------------------
[ubuntu:08544] 1 more process has sent help message help-mpi-errors.txt / mpi_errors_are_fatal
[ubuntu:08544] Set MCA parameter "orte_base_help_aggregate" to 0 to see all help / error messages

```

**Comment by aerialhedgehog** [comment]
and here's a trace from a unix cluster --

```
---------------------- Read Grid File Information -----------------------
Three dimensional problem.
3113133 points before parallel partitioning.
Performing linear partitioning of the grid nodes.
4478644 interior elements before parallel partitioning.
Distributing elements across all ranks.
Calling the partitioning functions.
Getting into adjacency function.
Building the graph adjacency structure.
8 surface markers.
166730 boundary elements in index 0 (Marker = aircraft).
33766 boundary elements in index 1 (Marker = farfield).
742 boundary elements in index 2 (Marker = injest).
290 boundary elements in index 3 (Marker = inlet).
22500 boundary elements in index 4 (Marker = inner_nearfield).
243 boundary elements in index 5 (Marker = outlet).
146871 boundary elements in index 6 (Marker = symmetry).
22500 boundary elements in index 7 (Marker = outer_nearfield).
Calling ParMETIS...
Fatal error in MPI_Wait:
Message truncated, error stack:
MPI_Wait(156).....................: MPI_Wait(request=0x106b830,
status0x106b6e0) failed
MPIDI_CH3U_Receive_data_found(259): Message from rank 0 and tag 1
truncated; 36096 bytes received but buffer size is 32032
Fatal error in MPI_Wait:
Message truncated, error stack:
MPI_Wait(156).....................: MPI_Wait(request=0x106b830,
status0x106b6e0) failed
MPIDI_CH3U_Receive_data_found(259): Message from rank 0 and tag 1
truncated; 36400 bytes received but buffer size is 32032
Fatal error in MPI_Wait:
Message truncated, error stack:
MPI_Wait(156).....................: MPI_Wait(request=0x106b830,
status0x106b6e0) failed
MPIDI_CH3U_Receive_data_found(259): Message from rank 0 and tag 1
truncated; 35800 bytes received but buffer size is 31680
Fatal error in MPI_Wait:
Message truncated, error stack:
MPI_Wait(156).....................: MPI_Wait(request=0x106b830,
status0x106b6e0) failed
MPIDI_CH3U_Receive_data_found(259): Message from rank 0 and tag 1
truncated; 36368 bytes received but buffer size is 32032
Fatal error in MPI_Wait:
Message truncated, error stack:
MPI_Wait(156).....................: MPI_Wait(request=0x106b830,
status0x106b6e0) failed
MPIDI_CH3U_Receive_data_found(259): Message from rank 0 and tag 1
truncated; 36088 bytes received but buffer size is 32032
Fatal error in MPI_Wait:
Message truncated, error stack:
MPI_Wait(156).....................: MPI_Wait(request=0x106b830,
status0x106b6e0) failed
MPIDI_CH3U_Receive_data_found(259): Message from rank 0 and tag 1
truncated; 1128 bytes received but buffer size is 1056
```

**Comment by btracey** [comment]
I haven't interacted with ParMETIS, but vtxdist looks fishy. It's an array of size "size+1", but it's only initialized up to "size"

**Comment by btracey** [comment]
Nope, that's a lie. Sorry.

**Comment by fpalacios** [comment]
I think I have found the problem,

I’ll commit a fix soon.

Cheers,
Francisco

**Comment by btracey** [comment]
Thanks Francisco.

**Comment by aerialhedgehog** [comment]
many thanks!

**Comment by priyanshi456** [comment]
Hi,

What is the fix for the problem?
I am getting this error on increasing the number of nodes.
