### ISSUE TITLE
Unable to build the SU2_CFD_AD and codi for shape_optimization.py

### ISSUE THREAD

**Issue by HANSIeltsKing** [su2code/SU2#1602]
Hi, I'm in trouble with the shape_optimization.py. I'm following the instructions of the tutorial for unsteady shape optimization for naca0012 but got an error:

```
Traceback (most recent call last):
  File "/usr/local/bin/shape_optimization.py", line 166, in <module>
    main()
  File "/usr/local/bin/shape_optimization.py", line 92, in main
    shape_optimization( options.filename    ,
  File "/usr/local/bin/shape_optimization.py", line 142, in shape_optimization
    SU2.opt.SLSQP(project,x0,xb,its,accu)
  File "/usr/local/bin/SU2/opt/scipy_tools.py", line 120, in scipy_slsqp
    outputs = fmin_slsqp( x0             = x0             ,
  File "/home/xxx/.local/lib/python3.8/site-packages/scipy/optimize/_slsqp_py.py", line 206, in fmin_slsqp
    res = _minimize_slsqp(func, x0, args, jac=fprime, bounds=bounds,
  File "/home/xxx/.local/lib/python3.8/site-packages/scipy/optimize/_slsqp_py.py", line 374, in _minimize_slsqp
    sf = _prepare_scalar_function(func, x, jac=jac, args=args, epsilon=eps,
  File "/home/xxx/.local/lib/python3.8/site-packages/scipy/optimize/_optimize.py", line 263, in _prepare_scalar_function
    sf = ScalarFunction(fun, x0, args, grad, hess,
  File "/home/xxx/.local/lib/python3.8/site-packages/scipy/optimize/_differentiable_functions.py", line 177, in __init__
    self._update_grad()
  File "/home/xxx/.local/lib/python3.8/site-packages/scipy/optimize/_differentiable_functions.py", line 256, in _update_grad
    self._update_grad_impl()
  File "/home/xxx/.local/lib/python3.8/site-packages/scipy/optimize/_differentiable_functions.py", line 167, in update_grad
    self.g = grad_wrapped(self.x)
  File "/home/xxx/.local/lib/python3.8/site-packages/scipy/optimize/_differentiable_functions.py", line 164, in grad_wrapped
    return np.atleast_1d(grad(np.copy(x), *args))
  File "/usr/local/bin/SU2/opt/scipy_tools.py", line 400, in obj_df
    dobj_list = project.obj_df(x)
  File "/usr/local/bin/SU2/opt/project.py", line 238, in obj_df
    return self._eval(konfig, func,dvs)
  File "/usr/local/bin/SU2/opt/project.py", line 202, in _eval
    vals = design._eval(func,*args)
  File "/usr/local/bin/SU2/eval/design.py", line 147, in _eval
    vals = eval_func(*inputs)
  File "/usr/local/bin/SU2/eval/design.py", line 380, in obj_df
    grad = su2grad(this_obj,grad_method,config,state)
  File "/usr/local/bin/SU2/eval/gradients.py", line 96, in gradient
    grads = adjoint( func_name, config, state )
  File "/usr/local/bin/SU2/eval/gradients.py", line 294, in adjoint
    info = su2run.adjoint(konfig)
  File "/usr/local/bin/SU2/run/adjoint.py", line 79, in adjoint
    SU2_CFD(konfig)
  File "/usr/local/bin/SU2/run/interface.py", line 112, in CFD
    run_command( the_Command )
  File "/usr/local/bin/SU2/run/interface.py", line 292, in run_command
    raise exception(message)
RuntimeError: Path = /home/xxx/SU2/SU2-7.0.4/test1/DESIGNS/DSN_001/ADJOINT_DRAG/,
Command = /home/xxx/SU2/SU2-7.0.4/SU2_CFD/bin/SU2_CFD_AD config_CFD_AD.cfg
SU2 process returned error '127'
/bin/sh: 1: /home/xxx/SU2/SU2-7.0.4/SU2_CFD/bin/SU2_CFD_AD: not found
```
So I tried to build AD under the instruction. I copied the exact same thing and pasted to the command. The error is:

```
Checking the status of submodules
=====================================================================
Found an old or unspecified version of CoDiPack in externals/codi.
Use -u to reset module.
```
However, when I try to update/reinstall the codi, I failed in the extraction process. The error is:
```
Checking the status of submodules
=====================================================================

git command failed (either git is not installed or this is not a git repository).

Using fall-back method to initialize submodule CoDiPack

Initializing CoDiPack 'bd4a639c2fe625a80946c8365bd2976a2868cf46'
=====================================================================
Downloading module from https://github.com/scicompkl/CoDiPack
Extracting archive ...
Extraction of module CoDiPack failed. See preconf.err for more information.
```
So how can I build the SU2_CFD_AD and run the shape_optimization.py? Thank you very much.

All the direct solutions can work well.
My SU2 version is 7.0.4 under Linux system.

**Comment by pcarruscag** [comment]
Try using a recent version.
