### ISSUE TITLE
Divergence optimization NACA0012 inviscid test-cases

### ISSUE THREAD

**Issue by arrow206** [su2code/SU2#170]
I am using SU2 version 3.2.8 on a Linux workstation.
I am trying to optimize an NACA0012 for Euler flow Test_cases/Optimization_euler/steady_naca0012).
The code diverged after 115 call to functions. I am including the output.
If I am trying to read the error, it seems there is an issue with slsqp that
is provided by Python. If this is the cases, what Scipy version of Python would you recommend?

python shape_optimization.py -f inv_NACA0012_adv.cfg -r 0

-------------------------------------------------------------------------
|    ___ _   _ ___                                                      |
|   / __| | | |_  )   Release 3.2.8 "eagle"                             |
|   \__ \ |_| |/ /                                                      |
|   |___/\___//___|   Aerodynamic Shape Optimization Script             |
|                                                                       |
----------------------------------------------------------------

  NIT    FC           OBJFUN            GNORM
    1     1     2.134595E-05     1.958771E-02
    2     6     2.134988E-05     1.958696E-02
    3    13     2.134986E-05     1.958707E-02
    4    24     2.134983E-05     1.958709E-02
    5    35     2.134980E-05     1.958711E-02
    6    46     2.134976E-05     1.958720E-02
    7    54     2.134978E-05     1.958710E-02
    8    65     2.134975E-05     1.958720E-02
    9    76     2.134973E-05     1.958720E-02
   10    87     2.134973E-05     1.958720E-02
   11    98     2.134970E-05     1.958720E-02
   12   104     2.134968E-05     1.958720E-02
   13   115     2.134967E-05     1.958720E-02
Traceback (most recent call last):
  File "shape_optimization.py", line 154, in <module>
    main()
  File "shape_optimization.py", line 99, in main
    options.quiet        )
  File "shape_optimization.py", line 137, in shape_optimization
    SU2.opt.SLSQP(project,x0,xb,its,accu)
  File "/home/fortin/Python/bin/SU2/opt/scipy_tools.py", line 128, in scipy_slsqp
    epsilon        = eps            )
  File "/usr/lib64/python2.6/site-packages/scipy/optimize/slsqp.py", line 206, in fmin_slsqp
    constraints=cons, **opts)
  File "/usr/lib64/python2.6/site-packages/scipy/optimize/slsqp.py", line 364, in _minimize_slsqp
    fx = func(x)
  File "/usr/lib64/python2.6/site-packages/scipy/optimize/optimize.py", line 282, in function_wrapper
    return function(*(wrapper_args + args))
  File "/home/fortin/Python/bin/SU2/opt/scipy_tools.py", line 144, in obj_f
    obj = project.obj_f(x)
  File "/home/fortin/Python/bin/SU2/opt/project.py", line 211, in obj_f
    return self._eval(konfig, func,dvs)
  File "/home/fortin/Python/bin/SU2/opt/project.py", line 180, in _eval
    vals = design._eval(func,*args)
  File "/home/fortin/Python/bin/SU2/eval/design.py", line 142, in _eval
    vals = eval_func(*inputs)
  File "/home/fortin/Python/bin/SU2/eval/design.py", line 240, in obj_f
    func = su2func(this_obj,config,state)
  File "/home/fortin/Python/bin/SU2/eval/functions.py", line 85, in function
    aerodynamics( config, state )
  File "/home/fortin/Python/bin/SU2/eval/functions.py", line 224, in aerodynamics
    info = su2run.direct(config)
  File "/home/fortin/Python/bin/SU2/run/direct.py", line 79, in direct
    SU2_CFD(konfig)
  File "/home/fortin/Python/bin/SU2/run/interface.py", line 88, in CFD
    run_command( the_Command )
  File "/home/fortin/Python/bin/SU2/run/interface.py", line 276, in run_command
    raise exception , message
SU2.DivergenceFailure: Path = /home/fortin/Python/DESIGNS/DSN_116/DIRECT/,
Command = mpirun -n 1 /home/fortin/Python/bin/SU2_CFD config_CFD.cfg
SU2 process returned error '2'
--------------------------------------------------------------------------
mpirun noticed that the job aborted, but has no info as to the process
that caused that situation.
--------------------------------------------------------------------------

**Comment by demanosalvas** [comment]
Hey Arrow206, 

Would you mind posting this question on the Forum?
http://www.cfd-online.com/Forums/su2/

David

**Comment by arrow206** [comment]
No problem. It can be posted on the Forum. Sorry if I put in in the bad place.
