### ISSUE TITLE
shape_optimization.py produced Keyerror: 'Config parameter not found: OPT_OBJECTIVE'

### ISSUE THREAD

**Issue by wkangholy** [su2code/SU2#1714]
**Describe the bug**
*A clear and concise description of what the bug is and what you expect the behavior to be instead. If applicable, add screenshots to help explain your problem.*

As I used SU2 develop version for shape optimization, it gave a keyerror in TestCase 
disc_adj_rans/naca0012, 
shape_optimization.py -f turb_NACA0012_sa.cfg
and disc_adj_rans/cylinder,
shape_optimization.py -f cylinder_Windowing.cfg

I have compiled SU2 with AD enabled. 
Also try disc_adj_turbomachinery/transonic_stator_2d, gave the same error.
I would like to know if I make some mistakes to run the testcases.

**To Reproduce**
*Please provide a config file and mesh for a minimal example that recreates the problem.*

Found: mesh_cylinder.su2
New Project: ./
Traceback (most recent call last):
  File "/home/wkholy/su2/bin/SU2/io/config.py", line 164, in __getitem__
    return super(Config,self).__getitem__(k)
KeyError: 'OPT_OBJECTIVE'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/wkholy/su2/bin/shape_optimization.py", line 183, in <module>
    main()
  File "/home/wkholy/su2/bin/shape_optimization.py", line 92, in main
    shape_optimization( options.filename    ,
  File "/home/wkholy/su2/bin/shape_optimization.py", line 155, in shape_optimization
    project = SU2.opt.Project(config,state)
  File "/home/wkholy/su2/bin/SU2/opt/project.py", line 114, in __init__
    def_objs = config['OPT_OBJECTIVE']
  File "/home/wkholy/su2/bin/SU2/io/config.py", line 166, in __getitem__
    raise KeyError('Config parameter not found: %s' % k)
KeyError: 'Config parameter not found: OPT_OBJECTIVE'

**Desktop (please complete the following information):**
 - OS: [e.g., Linux (Redhat 6.6)]
 - C++ compiler and version: [e.g., g++ (GCC) 4.8.5]
 - MPI implementation and version: [e.g., OpenMPI 3.0.0]
 - SU2 Version: [e.g., v6.2.0]

Ubuntu 20.04
C++ gcc version 9.4.0
SU2 version 7.3.1 develop

**Comment by Eurus-Way** [comment]
您的邮件我已收到，我会尽快处理，祝好。                                                                       ——王络

**Comment by pcarruscag** [comment]
Have you tried one of the optimization tutorials?

**Comment by wkangholy** [comment]
I have run the tutorials successfully. The case is now running successfully.
