### ISSUE TITLE
Inverse Design test case

### ISSUE THREAD

**Issue by AbhijithMoni** [su2code/SU2#1725]
### Discussed in https://github.com/su2code/SU2/discussions/1715

<div type='discussions-op-text'>

<sup>Originally posted by **AbhijithMoni** July 18, 2022</sup>
Hi,

I'm running the inverse design case available in _`TestCases/optimization_euler/steady_inverse_design`_

While executing `python C:\SU2\bin\shape_optimization.py  -f .\inv_NACA0012.cfg`

The following error appears:

```
Traceback (most recent call last):
File "C:\SU2\bin\shape_optimization.py", line 183, in <module>
main()
File "C:\SU2\bin\shape_optimization.py", line 92, in main
shape_optimization( options.filename ,
File "C:\SU2\bin\shape_optimization.py", line 159, in shape_optimization
SU2.opt.SLSQP(project,x0,xb,its,accu)
File "C:\SU2\bin\SU2\opt\scipy_tools.py", line 120, in scipy_slsqp
outputs = fmin_slsqp( x0 = x0 ,
File "C:\ProgramData\Anaconda3\lib\site-packages\scipy\optimize\slsqp.py", line 207, in fmin_slsqp
res = _minimize_slsqp(func, x0, args, jac=fprime, bounds=bounds,
File "C:\ProgramData\Anaconda3\lib\site-packages\scipy\optimize\slsqp.py", line 375, in _minimize_slsqp
sf = _prepare_scalar_function(func, x, jac=jac, args=args, epsilon=eps,
File "C:\ProgramData\Anaconda3\lib\site-packages\scipy\optimize\optimize.py", line 261, in _prepare_scalar_function
sf = ScalarFunction(fun, x0, args, grad, hess,
File "C:\ProgramData\Anaconda3\lib\site-packages\scipy\optimize\_differentiable_functions. py", line 140, in __init__
self._update_fun()
File "C:\ProgramData\Anaconda3\lib\site-packages\scipy\optimize\_differentiable_functions. py", line 233, in _update_fun
self._update_fun_impl()
File "C:\ProgramData\Anaconda3\lib\site-packages\scipy\optimize\_differentiable_functions. py", line 137, in update_fun
self.f = fun_wrapped(self.x)
File "C:\ProgramData\Anaconda3\lib\site-packages\scipy\optimize\_differentiable_functions. py", line 134, in fun_wrapped
return fun(np.copy(x), *args)
File "C:\SU2\bin\SU2\opt\scipy_tools.py", line 383, in obj_f
obj_list = project.obj_f(x)
File "C:\SU2\bin\SU2\opt\project.py", line 237, in obj_f
return self._eval(konfig, func,dvs)
File "C:\SU2\bin\SU2\opt\project.py", line 206, in _eval
vals = design._eval(func,*args)
File "C:\SU2\bin\SU2\eval\design.py", line 147, in _eval
vals = eval_func(*inputs)
File "C:\SU2\bin\SU2\eval\design.py", line 244, in obj_f
func += su2func(this_obj,config,state) * sign * scale * global_factor
File "C:\SU2\bin\SU2\eval\functions.py", line 118, in function
func_out = state['FUNCTIONS'][func_name]
KeyError: 'INVERSE_DESIGN_PRESSURE' 
```

SU2 version - 7.2.0 
OS - Windows-11

I have also tried the latest version 7.3.1 on a Linux machine, I get the same error.

Please help me understand this error and fix it.

Thanks in advance. 
</div>

**Comment by pcarruscag** [comment]
Continued in #1727
