### ISSUE TITLE
Multipoint 2D Optimization Key Error

### ISSUE THREAD

**Issue by ugbourz** [su2code/SU2#1808]
Hi,
I want to processes a multipoint optimization with constraints. The problem I encountered is that, if I set the geometry based constraint is given to OPT_CONSTRAINT(e.g. OPT_CONSTRAINT=( AIRFOIL_THICKNESS>0)*0.001 like onepoint problem ), the error will occur as below. 
Traceback (most recent call last):
File "/home/star/su2/bin/shape_optimization.py", line 183, in <module>
main()
File "/home/star/su2/bin/shape_optimization.py", line 92, in main
shape_optimization( options.filename ,
File "/home/star/su2/bin/shape_optimization.py", line 159, in shape_optimization
SU2.opt.SLSQP(project,x0,xb,its,accu)
File "/home/star/su2/bin/SU2/opt/scipy_tools.py", line 120, in scipy_slsqp
outputs = fmin_slsqp( x0 = x0 ,
File "/usr/local/python/lib/python3.8/site-packages/scipy/optimize/_slsqp_py.py", line 206, in fmin_slsqp
res = _minimize_slsqp(func, x0, args, jac=fprime, bounds=bounds,
File "/usr/local/python/lib/python3.8/site-packages/scipy/optimize/_slsqp_py.py", line 374, in _minimize_slsqp
sf = _prepare_scalar_function(func, x, jac=jac, args=args, epsilon=eps,
File "/usr/local/python/lib/python3.8/site-packages/scipy/optimize/_optimize.py", line 263, in _prepare_scalar_function
sf = ScalarFunction(fun, x0, args, grad, hess,
File "/usr/local/python/lib/python3.8/site-packages/scipy/optimize/_differentiable_functions.py", line 158, in __init__
self._update_fun()
File "/usr/local/python/lib/python3.8/site-packages/scipy/optimize/_differentiable_functions.py", line 251, in _update_fun
self._update_fun_impl()
File "/usr/local/python/lib/python3.8/site-packages/scipy/optimize/_differentiable_functions.py", line 155, in update_fun
self.f = fun_wrapped(self.x)
File "/usr/local/python/lib/python3.8/site-packages/scipy/optimize/_differentiable_functions.py", line 137, in fun_wrapped
fx = fun(np.copy(x), *args)
File "/home/star/su2/bin/SU2/opt/scipy_tools.py", line 383, in obj_f
obj_list = project.obj_f(x)
File "/home/star/su2/bin/SU2/opt/project.py", line 237, in obj_f
return self._eval(konfig, func,dvs)
File "/home/star/su2/bin/SU2/opt/project.py", line 206, in _eval
vals = design._eval(func,*args)
File "/home/star/su2/bin/SU2/eval/design.py", line 147, in _eval
vals = eval_func(*inputs)
File "/home/star/su2/bin/SU2/eval/design.py", line 244, in obj_f
func += su2func(this_obj,config,state) * sign * scale * global_factor
File "/home/star/su2/bin/SU2/eval/functions.py", line 100, in function
multipoint( config, state )
File "/home/star/su2/bin/SU2/eval/functions.py", line 675, in multipoint
func[i+1] = aerodynamics(konfig,ztate)
File "/home/star/su2/bin/SU2/eval/functions.py", line 313, in aerodynamics
funcs[key] = state['FUNCTIONS'][key]
KeyError: 'AIRFOIL_AREA'

**Comment by EngJamal2023** [comment]
what is the solution for this problem
