### ISSUE TITLE
Dynamic Fluid-Structure Interaction Tutorial Bug 

### ISSUE THREAD

**Issue by himakarganti** [su2code/SU2#2129]
I am trying to get the Dynamic FSI tutorial to work and have rebuilt SU2 for the python wrapper, as well as install all dependencies, including mpi4py, petsc and petsc4py. I am getting the following error and the **_fsi_computation.py_** file is showing that the **_allMarkersID_** variable has no attribute for **_keys_**. I am running the case with Ubuntu 20.04 with openmpi and python 3.8. Can someone please let me know what is causing this issue/ bug?

 Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.8/dist-packages/mpi4py/__main__.py", line 7, in <module>
    main()
  File "/usr/local/lib/python3.8/dist-packages/mpi4py/run.py", line 198, in main
    run_command_line(args)
  File "/usr/local/lib/python3.8/dist-packages/mpi4py/run.py", line 47, in run_command_line
    run_path(sys.argv[0], run_name='__main__')
  File "/usr/lib/python3.8/runpy.py", line 265, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/usr/lib/python3.8/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/path/to/folder/SU2/SU2_PY/fsi_computation.py", line 259, in <module>
    main()
  File "/path/to/folder/SU2/SU2_PY/fsi_computation.py", line 165, in main
    FSIInterface.connect(FSI_config, FluidSolver, SolidSolver)
  File "/path/to/folder/SU2/SU2_PY/FSI_tools/FSIInterface.py", line 314, in connect
    if allMovingMarkersTags[0] in allMarkersID.keys():
AttributeError: 'tuple' object has no attribute 'keys'

**Comment by pcarruscag** [comment]
@Nicola-Fonzi is this something you've seen before?

**Comment by Nicola-Fonzi** [comment]
Dear @himakarganti, sorry for the very late reply, I completely missed your question. May I ask you which version are you using?

**Comment by alicezanella** [comment]
Hi everyone, 

I'm facing the same problem too. I'm using the latest master version built with the python wrapper. 

Seems like allMarkersID is a tuple and not a dictionary. 

Thank you, 
Alice

**Comment by TurboLdd** [comment]
> Dear @himakarganti, sorry for the very late reply, I completely missed your question. May I ask you which version are you using?

Hi, I can explain the issue. It is about conducting unsteady fsi computation using Python. In the FSIInterface.connect(), the dictionary should be used. But after  [https://github.com/su2code/SU2/pull/1300](url) , the function returning dictionary was modified and return a list. Actually, I encounter this problem in 8.0.0 too.

**Comment by bsonic15** [comment]
Hi everyone,

I am having this same issue, was a solution found the last time the error was encountered?

Any help would be greatly appreciated.

Thanks alot,
B

**Comment by bigfooted** [comment]
This issue has been fixed and merged into develop. Thank you all for your contributions
