### ISSUE TITLE
./ninja -C build install error

### ISSUE THREAD

**Issue by vanessachung97** [su2code/SU2#2199]
Hi, i am trying to install SU2 on my computer and after running ./ninja -C build install, this is the error I am getting:

1 warning generated.
[658/711] Compiling C++ object SU2_CFD/s...core.a.p/drivers_CSinglezo[659/711] Compi[660/711] Compiling C++ object SU2_CFD/s...p/drivers_C[672/711] Compilin[696/711] Linking static target SU2_CFD/src/libSU2core.a
/Library/Developer/CommandLineTools/usr/bin/ranlib: file: SU2_CFD/src/libSU2core.a(fluid_CMutationTCLib.cpp.o) has no symbols
/Library/Developer/CommandLineTools/usr/bin/ranlib: file: SU2_CFD/src/libSU2core.a(numerics_scalar_scalar_sources.cpp.o) has no symbols
[701/711] Linking target SU2_SOL/src/SU2_SOL
ld: warning: -undefined error is deprecated
ld: warning: ignoring duplicate libraries: '-lz'
[703/711] Linking target SU2_GEO/src/SU2_GEO
ld: warning: -undefined error is deprecated
ld: warning: ignoring duplicate libraries: '-lz'
[705/711] Linking target SU2_CFD/src/SU2_CFD
ld: warning: -undefined error is deprecated
ld: warning: ignoring duplicate libraries: '-lz'
[707/711] Linking target SU2_DEF/src/SU2_DEF
ld: warning: -undefined error is deprecated
ld: warning: ignoring duplicate libraries: '-lz'
[710/711] Linking target SU2_DOT/src/SU2_DOT
ld: warning: -undefined error is deprecated
ld: warning: ignoring duplicate libraries: '-lz'
[710/711] Installing files.
Installing SU2_CFD/src/SU2_CFD to /usr/local/bin
Traceback (most recent call last):
  File "/Users/vanessachung/Downloads/SU2-8.0.0/externals/meson/mesonbuild/mesonmain.py", line 146, in run
    return options.run_func(options)
  File "/Users/vanessachung/Downloads/SU2-8.0.0/externals/meson/mesonbuild/minstall.py", line 811, in run
    installer.do_install(datafilename)
  File "/Users/vanessachung/Downloads/SU2-8.0.0/externals/meson/mesonbuild/minstall.py", line 587, in do_install
    self.install_targets(d, dm, destdir, fullprefix)
  File "/Users/vanessachung/Downloads/SU2-8.0.0/externals/meson/mesonbuild/minstall.py", line 730, in install_targets
    file_copied = self.do_copyfile(fname, outname, makedirs=(dm, outdir))
  File "/Users/vanessachung/Downloads/SU2-8.0.0/externals/meson/mesonbuild/minstall.py", line 458, in do_copyfile
    self.copy2(from_file, to_file)
  File "/Users/vanessachung/Downloads/SU2-8.0.0/externals/meson/mesonbuild/minstall.py", line 353, in copy2
    shutil.copy2(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/shutil.py", line 432, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/shutil.py", line 261, in copyfile
    with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
PermissionError: [Errno 13] Permission denied: '/usr/local/bin/SU2_CFD'

ERROR: Unhandled python exception

    This is a Meson bug and should be reported!
FAILED: meson-install 
/Library/Frameworks/Python.framework/Versions/3.9/bin/python3 /Users/vanessachung/Downloads/SU2-8.0.0/meson.py install --no-rebuild

**Desktop (please complete the following information):**
 - OS: Mac M1
 - C++ compiler and version: Apple clang version 15.0.0 (clang-1500.1.0.2.5)
 - SU2 Version: v8.0.0

**Comment by vanessachung97** [comment]
Not a bug, installed using sudo ./ninja -C build install and it worked.
