### ISSUE TITLE
OSError: [Errno 2] No such file or directory: 'of_grad_cd.dat'

### ISSUE THREAD

**Issue by Xwang1976** [su2code/SU2#388]
Running serial_regression.py I get the following error:
==================== Start Test: contadj_euler_py ====================
/home/andreak/tmp/AUR/su2/src/SU2/TestCases/cont_adj_euler/naca0012
Traceback (most recent call last):
  File "/opt/su2/bin/continuous_adjoint.py", line 36, in <module>
    sys.path.append(os.environ['SU2_RUN'])
  File "/usr/lib/python3.6/os.py", line 669, in __getitem__
    raise KeyError(key) from None
KeyError: 'SU2_RUN'
Traceback (most recent call last):
  File "serial_regression.py", line 983, in <module>
    main()
  File "serial_regression.py", line 861, in main
    pass_list.append(contadj_euler_py.run_filediff())
  File "/home/andreak/tmp/AUR/su2/src/SU2/TestCases/TestCase.py", line 241, in run_filediff
    todate = time.ctime(os.stat(tofile).st_mtime)
OSError: [Errno 2] No such file or directory: 'of_grad_cd.dat'

**Comment by talbring** [comment]
Make sure to copy all files from the test case repository to the TestCases folder. Please reopen this issue if this has not been resolved with that.

**Comment by Xwang1976** [comment]
I've downloaded the TestCases directory with this command:
git clone git://github.com/su2code/TestCases.git
and still there is no of_grad_cd.dat file in the TestCases/cont_adj_euler/naca0012 folder.
So the problem is still present.

**Comment by Xwang1976** [comment]
How can I reopen this issue?
