### ISSUE TITLE
minstall.py fails on NFS filesystems

### ISSUE THREAD

**Issue by bmunguia** [su2code/SU2#937]
**Describe the bug**
This is an issue that @jayantmukho, @WallyMaier and I have seen when trying to build on Stanford's cluster with meson. Meson's call to `shutil.copystat()` fails, specifically on NFS filesystems, e.g.:
```
[649/650] Installing files.
Installing SU2_CFD/src/SU2_CFD to /home/groups/jjalonso/su2/wwv/bin
Traceback (most recent call last):
  File "/home/groups/jjalonso/su2/wwv/externals/meson/mesonbuild/mesonmain.py", line 129, in run
    return options.run_func(options)
  File "/home/groups/jjalonso/su2/wwv/externals/meson/mesonbuild/minstall.py", line 515, in run
    installer.do_install(datafilename)
  File "/home/groups/jjalonso/su2/wwv/externals/meson/mesonbuild/minstall.py", line 342, in do_install
    self.install_targets(d)
  File "/home/groups/jjalonso/su2/wwv/externals/meson/mesonbuild/minstall.py", line 449, in install_targets
    self.do_copyfile(fname, outname)
  File "/home/groups/jjalonso/su2/wwv/externals/meson/mesonbuild/minstall.py", line 258, in do_copyfile
    shutil.copystat(from_file, to_file)
  File "/share/software/user/open/python/3.6.1/lib/python3.6/shutil.py", line 225, in copystat
    _copyxattr(src, dst, follow_symlinks=follow)
  File "/share/software/user/open/python/3.6.1/lib/python3.6/shutil.py", line 164, in _copyxattr
    value = os.getxattr(src, name, follow_symlinks=follow_symlinks)
OSError: [Errno 22] Invalid argument: 'SU2_CFD/src/SU2_CFD'
```
Commenting out the call to `copystat()` in line 258 of minstall.py (which doesn't seem critical for the installation) seems to fix the issue.

I realize this isn't an issue specific to SU2, so I wanted peoples' opinions on how this should be handled. Just an addition to documentation?

**Desktop (please complete the following information):**
 - OS: CentOS 7.x
 - SU2 Version: v7.0.x

**Comment by talbring** [comment]
Hmm this seems to be a bug in python. It seems like in python 3.7 this problem is solved:
https://bugs.python.org/issue24564

Maybe use [conda](https://docs.conda.io/en/latest/) to change the python environment, if 3.7 is not installed on the cluster.

**Comment by bmunguia** [comment]
Yeah, looks like python 3.7 did the trick. I can update the installation documentation.

The init.py script checks that the python version is at least. Should we have it check that it's at least 3.7 instead?
